"use client";

import { api } from "@/lib/eden";
import { useEffect, useState, useCallback, useMemo } from "react";
import {
  AddButton,
  EditButton,
  ViewButton,
  DeleteButton,
  DuplicateButton,
  CancelButton,
  AcceptButton,
  CopyButton
} from "@/components/Buttons";
import { useTranslations } from "next-intl";
import { newErrorToast, newInfoToast } from "@/components/Toast";
import { AdminTable } from "@/components/admin/AdminTable";
import { textColumn, chipColumn, dateColumn } from "@/components/admin/AdminTableFactories";

type CertificateType = "COURSE_COMPLETION" | "EVENT_ACHIEVEMENT" | "PARTICIPATION" | "VOLUNTEER";

interface CertificateInterface {
  _id: string;
  title: string;
  type: CertificateType;
  recipientName: string;
  revoked: boolean;
  autoGenerated: boolean;
  createdAt: Date;
  isGroup?: boolean;
  count?: number;
  recipients?: Array<{ name: string; id: string }>;
}

type Props = {
  onCreate: () => void;
  onEdit: (id: string) => void;
  onView: (id: string) => void;
  onDelete: (id: string) => void;
  onDuplicate: (id: string) => void;
  onRevoke: (ids: string[]) => void;
  onReinstate: (ids: string[]) => void;
  refreshToken?: number;
  teamId?: string;
  hackathonId?: string;
  grouped?: boolean;
  createLabel?: string;
  teamName?: string;
};

const typeColors: Record<CertificateType, "primary" | "secondary" | "success" | "warning"> = {
  COURSE_COMPLETION: "primary",
  EVENT_ACHIEVEMENT: "success",
  PARTICIPATION: "secondary",
  VOLUNTEER: "warning"
};

export default function CertificateList({
  onCreate,
  onEdit,
  onView,
  onDelete,
  onDuplicate,
  onRevoke,
  onReinstate,
  refreshToken,
  teamId,
  hackathonId,
  grouped = false,
  createLabel,
  teamName
}: Props) {
  const t = useTranslations("admin.certificates.list");
  const [rows, setRows] = useState<CertificateInterface[]>([]);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState<CertificateType | "">("");
  const [includeRevoked, setIncludeRevoked] = useState(false);
  const [includeAutoGenerated, setIncludeAutoGenerated] = useState(Boolean(teamId || hackathonId));
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const PAGE_SIZE = 50;

  const load = useCallback(
    async (notify?: boolean) => {
      try {
        setLoading(true);
        const { data, error } = await api.admin.certificates.get({
          query: {
            search: search || undefined,
            type: typeFilter || undefined,
            includeRevoked: includeRevoked.toString(),
            includeAutoGenerated: includeAutoGenerated.toString(),
            page: page,
            pageSize: PAGE_SIZE,
            teamId,
            hackathonId,
            grouped: grouped ? "true" : undefined
          }
        });
        if (error) throw error;
        setTotal(data.total);
        setRows(
          data.items.map((x) => ({
            _id: x._id as string,
            title: x.title,
            type: x.type as CertificateType,
            recipientName: x.recipient?.name || t("multipleRecipients"),
            revoked: x.revoked?.isRevoked || false,
            autoGenerated: x.autoGenerated || false,
            createdAt: new Date(x.createdAt),
            isGroup: x.isGroup,
            count: x.count,
            recipients: x.recipients?.map((r) => ({
              name: r.name,
              id: r.id || ""
            }))
          }))
        );
        if (notify) {
          newInfoToast(t("reloaded"));
        }
      } catch (e) {
        console.error("Failed to load certificates:", e);
        setRows([]);
        newErrorToast(t("loadError"));
      } finally {
        setLoading(false);
      }
    },
    [
      search,
      typeFilter,
      includeRevoked,
      includeAutoGenerated,
      page,
      t,
      teamId,
      hackathonId,
      grouped
    ]
  );

  useEffect(() => {
    load();
  }, [load, refreshToken]);

  const columns = useMemo(() => {
    const allCols = [
      textColumn<CertificateInterface>("title", t("columns.title"), (r) => r.title, {
        bold: true,
        subValue: (r) => (r.isGroup ? `${r.count} ${t("recipients")}` : r._id)
      }),
      textColumn<CertificateInterface>("recipient", t("columns.recipient"), (r) => r.recipientName),
      chipColumn<CertificateInterface, CertificateType>(
        "type",
        t("columns.type"),
        (r) => r.type,
        (type) => t(`types.${type.toLowerCase()}`),
        (type) => typeColors[type]
      ),
      chipColumn<CertificateInterface, "active" | "revoked">(
        "status",
        t("columns.status"),
        (r) => (r.revoked ? "revoked" : "active"),
        (status) => t(`status.${status}`),
        (status) => (status === "active" ? "success" : "error"),
        "filled"
      ),
      chipColumn<CertificateInterface, "manual" | "auto">(
        "origin",
        t("columns.origin"),
        (r) => (r.autoGenerated ? "auto" : "manual"),
        (origin) => t(`origins.${origin}`),
        (origin) => (origin === "manual" ? "primary" : "secondary")
      ),
      dateColumn<CertificateInterface>("createdAt", t("columns.created"), (r) => r.createdAt)
    ];

    return grouped
      ? allCols.filter((c) => c.key !== "recipient" && c.key !== "title" && c.key !== "origin")
      : allCols;
  }, [t, grouped]);

  return (
    <AdminTable
      columns={columns}
      data={rows}
      loading={loading}
      onReload={() => load(true)}
      reloadLabel={t("reload")}
      headerActions={<AddButton onClick={onCreate}>{createLabel || t("create")}</AddButton>}
      rowActions={(r) => (
        <>
          {!grouped && <ViewButton onClick={() => onView(r._id)} iconSize={20} />}
          {grouped && (
            <CopyButton
              content={`${teamName ? teamName + "\n-----\n" : ""}${(r.recipients || [])
                .map((rec) => `${rec.name} - ${window.location.origin}/cert/${rec.id}`)
                .join("\n")}`}
              iconSize={20}
              ariaLabel={t("copyRecipients")}
              tooltip={t("copyRecipients")}
            />
          )}
          <EditButton onClick={() => onEdit(r._id)} iconSize={20} />
          {!grouped && (
            <DuplicateButton
              onClick={() => onDuplicate(r._id)}
              iconSize={20}
              ariaLabel={t("duplicate")}
              tooltip={t("duplicate")}
              confirmationDuration={1000}
            />
          )}
          {r.revoked ? (
            <AcceptButton
              onClick={() => {
                const ids = r.isGroup ? (r.recipients || []).map((x) => x.id) : [r._id];
                onReinstate(ids);
              }}
              color="success"
              iconSize={20}
              ariaLabel={t("reinstate")}
              tooltip={t("reinstate")}
              confirmationDuration={2000}
            />
          ) : (
            <CancelButton
              onClick={() => {
                const ids = r.isGroup ? (r.recipients || []).map((x) => x.id) : [r._id];
                onRevoke(ids);
              }}
              iconSize={20}
              ariaLabel={t("revoke")}
              tooltip={t("revoke")}
              confirmationDuration={2000}
            />
          )}
          <DeleteButton onClick={() => onDelete(r._id)} confirmationDuration={3000} iconSize={20} />
        </>
      )}
      search={{
        value: search,
        onChange: setSearch,
        placeholder: t("searchPlaceholder")
      }}
      filters={[
        {
          key: "type",
          label: t("filterType"),
          value: typeFilter,
          onChange: (v) => setTypeFilter(v as CertificateType | ""),
          options: [
            { label: t("allTypes"), value: "" },
            { label: t("types.courseCompletion"), value: "COURSE_COMPLETION" },
            { label: t("types.eventAchievement"), value: "EVENT_ACHIEVEMENT" },
            { label: t("types.participation"), value: "PARTICIPATION" },
            { label: t("types.volunteer"), value: "VOLUNTEER" }
          ],
          minWidth: "150px"
        },
        {
          key: "revoked",
          label: t("showRevoked"),
          value: includeRevoked ? "yes" : "no",
          onChange: (v) => setIncludeRevoked(v === "yes"),
          options: [
            { label: t("hideRevoked"), value: "no" },
            { label: t("showRevokedYes"), value: "yes" }
          ],
          minWidth: "140px"
        },
        ...(teamName
          ? []
          : [
              {
                key: "autoGenerated",
                label: t("showAutoGenerated"),
                value: includeAutoGenerated ? "yes" : "no",
                onChange: (v: string) => setIncludeAutoGenerated(v === "yes"),
                options: [
                  { label: t("hideAutoGenerated"), value: "no" },
                  { label: t("showAutoGeneratedYes"), value: "yes" }
                ],
                minWidth: "160px"
              }
            ])
      ]}
      pagination={{
        page,
        pageSize: PAGE_SIZE,
        total,
        onPageChange: setPage
      }}
      emptyMessage={t("noCertificates")}
      noResultsMessage={t("noResults")}
    />
  );
}
